USE gifts_db;

INSERT INTO gifts (gift_style, gift_name) VALUES 
('Active', 'athletic jacket'),
('Active', 'baseball shirt'),
('Active', 'basketball tank'),
('Active', 'bear tee'),
('Active', 'cycling shirt'),
('Active', 'dance-team jacket'),
('Active', 'diner apron'),
('Active', 'eight-ball tee'),
('Active', 'explorer shirt'),
('Simple', 'fischerhemd'),
('Active', 'fishing vest'),
('Active', 'fitness tank'),
('Active', 'five-ball tee'),
('Active', 'football shirt'),
('Active', 'four-ball tee'),
('Active', 'frog tee'),
('Active', 'groovy tunic'),
('Active', 'gym tee'),
('Active', 'handmade cape'),
('Active', 'heavy-duty shirt'),
('Active', 'kung-fu tee'),
('Active', 'mountain parka'),
('Active', 'muscle tank'),
('Active', 'music-fest shirt'),
('Active', 'nine-ball tee'),
('Active', 'one-ball tee'),
('Active', 'pullover jacket'),
('Active', 'rabbit tee'),
('Active', 'relay tank'),
('Active', 'rubber apron'),
('Active', 'safety vest'),
('Active', 'seven-ball tee'),
('Active', 'six-ball tee'),
('Active', 'sleeved apron'),
('Active', 'soccer-uniform top'),
('Active', 'thick-stripes shirt'),
('Active', 'three-ball tee'),
('Active', 'tie-dye shirt'),
('Active', 'track jacket'),
('Active', 'two-ball tee'),
('Active', 'western shirt'),
('Active', 'work apron'),
('Active', 'workers jacket'),
('Active', 'workout top'),
('Active', 'zigzag shirt'),
('Cool', 'after-school jacket'),
('Cool', 'biker jacket'),
('Cool', 'bomber-style jacket'),
('Cool', 'bug aloha shirt'),
('Cool', 'bulldog jacket'),
('Cool', 'business suitcoat'),
('Cool', 'camo bomber-style jacket'),
('Cool', 'chesterfield coat'),
('Cool', 'DAL pilot jacket'),
('Cool', 'earbuds combo'),
('Cool', 'groovy shirt'),
('Cool', 'Labelle knit shirt'),
('Cool', 'samurai shirt'),
('Cool', 'space parka'),
('Cool', 'text shirt'),
('Cool', 'thiefs costume'),
('Cool', 'thread-worn sweater'),
('Cool', 'tuxedo jacket'),
('Cool', 'vampire costume'),
('Cool', 'viking top'),
('Cool', 'work shirt'),
('Cute', 'dotted raincoat'),
('Cute', 'heart apron'),
('Cute', 'holiday sweater'),
('Cute', 'kids smock'),
('Cute', 'Moms hand-knit sweater'),
('Cute', 'Moms handmade apron'),
('Cute', 'silk floral-print shirt'),
('Elegant', 'cafe uniform'),
('Elegant', 'cavalier shirt'),
('Elegant', 'Chimayo vest'),
('Elegant', 'colorful striped sweater'),
('Elegant', 'detectives coat'),
('Elegant', 'emblem blazer'),
('Elegant', 'hand-knit tank'),
('Elegant', 'military uniform'),
('Elegant', 'misty tee'),
('Elegant', 'morning coat'),
('Elegant', 'peasant blouse'),
('Elegant', 'poncho-style sweater'),
('Elegant', 'princes tunic'),
('Elegant', 'silk shirt'),
('Elegant', 'sweater on shirt'),
('Elegant', 'sweetheart tank and shirt'),
('Elegant', 'tailcoat'),
('Elegant', 'trench coat'),
('Elegant', 'tweed jacket'),

('Gorgeous', 'comedians outfit'),
('Gorgeous', 'flashy cardigan'),
('Gorgeous', 'flashy jacket'),
('Gorgeous', 'Labelle coat'),
('Gorgeous', 'noble coat'),
('Gorgeous', 'old-school jacket'),
('Gorgeous', 'royal shirt'),
('Gorgeous', 'young-royal shirt'),
('Simple', 'A tee'),
('Simple', 'acid-washed jacket'),
('Simple', 'annyeong tee'),
('Simple', 'anorak jacket'),
('Simple', 'apron'),
('Simple', 'argyle vest'),
('Simple', 'baggy shirt'),
('Simple', 'big-star tee'),
('Simple', 'bonjour tee'),
('Simple', 'camper tee'),
('Simple', 'cardigan-shirt combo'),
('Simple', 'career jacket'),
('Simple', 'chefs outfit'),
('Simple', 'ciao tee'),
('Simple', 'collarless coat'),
('Simple', 'college cardigan'),
('Simple', 'color-block dress shirt'),
('Simple', 'Coral Nook Inc. aloha shirt'),
('Simple', 'cowboy shirt'),
('Simple', 'DAL apron'),
('Simple', 'DAL tee'),
('Simple', 'denim jacket'),
('Simple', 'doctors coat'),
('Simple', 'doublet'),
('Simple', 'dress shirt'),
('Simple', 'energetic sweater'),
('Simple', 'fischerhemd'),
('Simple', 'fish-print tee'),
('Simple', 'flannel shirt'),
('Simple', 'fuzzy vest'),
('Simple', 'gingham picnic shirt'),
('Simple', 'graduation gown'),
('Simple', 'Green Nook Inc. aloha shirt'),
('Simple', 'guide shirt'),
('Simple', 'hallo tee'),
('Simple', 'hello tee'),
('Simple', 'henley shirt'),
('Simple', 'hi tee'),
('Simple', 'hoi tee'),
('Simple', 'hola tee'),
('Simple', 'humble sweater'),
('Simple', 'konnichiwa tee'),
('Simple', 'kurta'),
('Simple', 'layered shirt'),
('Simple', 'multipurpose vest'),
('Simple', 'MVP tee'),
('Simple', 'ni hao tee'),
('Simple', 'No. 1 shirt'),
('Simple', 'No. 2 shirt'),
('Simple', 'No. 3 shirt'),
('Simple', 'No. 4 shirt'),
('Simple', 'Nook Inc. aloha shirt'),
('Simple', 'Nook Inc. blouson'),
('Simple', 'Nook Inc. tee'),
('Simple', 'nurses jacket'),
('Simple', 'OK Motors jacket'),
('Simple', 'open-collar shirt'),
('Simple', 'printed layered shirt'),
('Simple', 'printed-sleeve sweater'),
('Simple', 'privet tee'),
('Simple', 'raglan shirt'),
('Simple', 'raincoat'),
('Simple', 'sailor-style shirt'),
('Simple', 'school jacket'),
('Simple', 'simple parka'),
('Simple', 'sports tank'),
('Simple', 'staff uniform'),
('Simple', 'striped shirt'),
('Simple', 'sushi chefs outfit'),
('Simple', 'sweater-vest'),
('Simple', 'sweatshirt'),
('Simple', 'tailored jacket'),
('Simple', 'tee-parka combo'),
('Simple', 'tennis sweater'),
('Simple', 'tight-knit sweater'),
('Simple', 'top coat'),
('Simple', 'traditional straw coat'),
('Simple', 'tweed vest'),
('Simple', 'V-neck sweater'),
('Simple', 'vest with binoculars'),
('Simple', 'waistcoat');

SELECT * FROM gifts;